### PR TITLE
Add man page for nitrocli(1) version 0.2.2

### PR DESCRIPTION
**Pull request by d-e-s-o**
This change adds a man page for nitrocli version 0.2.2 to the
repository.

### CODE REVIEW

**Comment by jacksonp** [comment]
Many thanks for the pull request, this page is now available: https://www.mankier.com/1/nitrocli

**Comment by d-e-s-o** [comment]
Very nice, thank you! :)

**Comment by d-e-s-o** [comment]
Two quick questions, @jacksonp:
1) I noticed that `nitrocli` is not listed on https://www.mankier.com/1/ . Is that intentional?
2) The `nitrocli otp set slot name secret` and `nitrocli config set` lines are overly long. It appears as if that is a bug. Should I open an issue for that or is that by design?

**Comment by d-e-s-o** [comment]
Awesome, thank you for the quick fixes!

**Pull request merged**
